### ISSUE TITLE
Misp2 looses all query parameters of a REST service while proxying requests

### ISSUE THREAD

**Issue by aasaru** [nordic-institute/misp2#7]
I have a REST service and I try to call it using the latest MISP2 (I'm using the Docker version found in docker-dev).
My OpenAPI based service has defined some optional query paramters like this:

```
        - in: query
          name: myParam
          description: myParam
          required: false
          schema:
            type: string
```

I have generated a form in Misp2 and I can fill in the value of "myParam"
However when I submit the form all the values (that had in:query in the yaml) are lost by MISP2.

It seems this code lacks copying over the query params:
https://github.com/nordic-institute/misp2/blob/develop/web-app/src/main/java/ee/aktors/misp2/action/RestMediatorAction.java#L235-L289

How to test:
1. import this OpenAPI yaml into Misp2 and generate forms
https://x-tee.ee/catalogue-data/ee-dev/ee-dev/COM/11333578/rest-service-01/petstore_1.yaml
2. Open the service "Get pets from store"

As you can see from the yaml it has a query parameter "name":

```
paths:
  /pets:
    get:
      tags:
        - pet
      summary: Get pets from store
      description: Search pets
      operationId: getPets
      parameters:
        - name: name
          in: query
          description: Pet name search
          required: false
          schema:
            type: string
```

3. When you fill in the form and set name to value "doggy" and submit you will notice that MISP2 hits URL "/pets" (without any query parameters) but it should try to open "/pets?name=doggy"
