### ISSUE TITLE
date-time parameters don't work (time is not sent out and date is in wrong format)

### ISSUE THREAD

**Issue by aasaru** [nordic-institute/misp2#9]
I have a REST web service with date-time header parameter:

```
        - in: header
          name: If-Modified-Since
          schema:
            type: string
            format: date-time
            example: 2022-10-18T17:32:28+02:00
          required: false
```

MISP2 UI renders a nice datepicker and a checkbox to enter time:
![misp2-date-time-rendered](https://user-images.githubusercontent.com/6773052/201927445-41ef8228-355b-4a1b-ace8-0b2bbf42f9d6.png)

I set date to "14.11.2022" and time to "16:52" submit the form this what is show in the logs:

This is what is logged and sent out to the service:

Headers     : 
   if-modified-since: 11/14/2022

Expected behaviour would be that date would be in correct format (yyyy-mm-dd) and time would be appended to it like this:

Headers     : 
   if-modified-since: 2022-11-14T16:52:00+02:00
